language: generic

services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=master

env:
  - EMACS_VERSION=26.2
  - EMACS_VERSION=26.1
  - EMACS_VERSION=25.3
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.1
  - EMACS_VERSION=24.5
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.2
  - EMACS_VERSION=24.1
script:
  - |
    docker run -i --rm -v $(pwd):/root/.emacs.d silex/emacs:"$EMACS_VERSION-alpine" emacs -batch -l /root/.emacs.d/init.el <<EOF
    y
    EOF
