language: emacs-lisp

sudo: required
dist: trusty
cache:
  - directories:
      - "$HOME/emacs/"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=26.1
  - EMACS_VERSION=26.2-rc1 PRETEST=yes
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
script:
  - ln -s $(pwd) ~/.emacs.d
  - |
    emacs -batch -l init.el <<EOF
    y
    EOF
